### PR TITLE
Fix the job configuration error...

### PR DESCRIPTION
**Pull request by robinsoc**
... When a bad URL is given in the Global Configuration menu

### CODE REVIEW

**Comment by vaceletm** [comment]
What's the original problem? I don't know how to reproduce the error

**Comment by robinsoc** [comment]
When you write a bad URL (e.g https://www.tuleap.example.test ) in the Configuration System and if you want to configure a new job an error is thrown by Jenkins.

**Comment by vaceletm** [comment]
Doesn't seems to work as expected

**Comment by robinsoc** [comment]
It should be ok now

**Pull request merged**
